#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP12_PaperDoll_Mannequin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP12_PaperDoll_Mannequin.BP12_PaperDoll_Mannequin_C
// 0x0008 (0x0460 - 0x0458)
class ABP12_PaperDoll_Mannequin_C final : public AFortPlayerMannequin
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0458(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP12_PaperDoll_Mannequin(int32 EntryPoint);
	void OnPartChanged(const class UCustomCharacterPart* OldPart, const class UCustomCharacterPart* NewPart, EFortCustomPartType PartType);
	void OnVariantChanged(const struct FGameplayTag& VariantChannel, const struct FGameplayTag& OldVariantTag, const struct FGameplayTag& NewVariantTag);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP12_PaperDoll_Mannequin_C">();
	}
	static class ABP12_PaperDoll_Mannequin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP12_PaperDoll_Mannequin_C>();
	}
};
static_assert(alignof(ABP12_PaperDoll_Mannequin_C) == 0x000008, "Wrong alignment on ABP12_PaperDoll_Mannequin_C");
static_assert(sizeof(ABP12_PaperDoll_Mannequin_C) == 0x000460, "Wrong size on ABP12_PaperDoll_Mannequin_C");
static_assert(offsetof(ABP12_PaperDoll_Mannequin_C, UberGraphFrame) == 0x000458, "Member 'ABP12_PaperDoll_Mannequin_C::UberGraphFrame' has a wrong offset!");

}

