#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChallengeListEntry_Header

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeListEntry_Header.ChallengeListEntry_Header_C
// 0x0010 (0x0278 - 0x0268)
class UChallengeListEntry_Header_C final : public UAthenaChallengeListEntry_Header
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetSwitcher*                        SwitcherPaidFreeIcon;                              // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ChallengeListEntry_Header(int32 EntryPoint);
	void OnSectionTypeSet(EChallengeListSection SectionType);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChallengeListEntry_Header_C">();
	}
	static class UChallengeListEntry_Header_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeListEntry_Header_C>();
	}
};
static_assert(alignof(UChallengeListEntry_Header_C) == 0x000008, "Wrong alignment on UChallengeListEntry_Header_C");
static_assert(sizeof(UChallengeListEntry_Header_C) == 0x000278, "Wrong size on UChallengeListEntry_Header_C");
static_assert(offsetof(UChallengeListEntry_Header_C, UberGraphFrame) == 0x000268, "Member 'UChallengeListEntry_Header_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UChallengeListEntry_Header_C, SwitcherPaidFreeIcon) == 0x000270, "Member 'UChallengeListEntry_Header_C::SwitcherPaidFreeIcon' has a wrong offset!");

}

