#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Fortnite_Base_Tail_AnimBP

#include "Basic.hpp"

#include "Fortnite_Base_Tail_AnimBP_classes.hpp"
#include "Fortnite_Base_Tail_AnimBP_parameters.hpp"


namespace SDK
{

// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.ExecuteUbergraph_Fortnite_Base_Tail_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFortnite_Base_Tail_AnimBP_C::ExecuteUbergraph_Fortnite_Base_Tail_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "ExecuteUbergraph_Fortnite_Base_Tail_AnimBP");

	Params::Fortnite_Base_Tail_AnimBP_C_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFortnite_Base_Tail_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "BlueprintUpdateAnimation");

	Params::Fortnite_Base_Tail_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.AnimNotify_RollRandomIdle
// (BlueprintCallable, BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::AnimNotify_RollRandomIdle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "AnimNotify_RollRandomIdle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.AnimNotify_JumpLandExit
// (BlueprintCallable, BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::AnimNotify_JumpLandExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "AnimNotify_JumpLandExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_6D073FA240E82B3DDA2C4CB6B8D6E215
// (BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_6D073FA240E82B3DDA2C4CB6B8D6E215()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_6D073FA240E82B3DDA2C4CB6B8D6E215");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_B2A9002E421DC72E5ED848899CD3DEF6
// (BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_B2A9002E421DC72E5ED848899CD3DEF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_B2A9002E421DC72E5ED848899CD3DEF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_C5B779F8485834C4DC389A98B0B43B31
// (BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_C5B779F8485834C4DC389A98B0B43B31()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_C5B779F8485834C4DC389A98B0B43B31");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_62D9552B41666E676B55159211408DD0
// (BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_62D9552B41666E676B55159211408DD0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_62D9552B41666E676B55159211408DD0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_0421F1ED47466E02393D109D708977F7
// (BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_0421F1ED47466E02393D109D708977F7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_0421F1ED47466E02393D109D708977F7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_4E73C08A41114BBB798C98BAF38B00DB
// (BlueprintEvent)

void UFortnite_Base_Tail_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_4E73C08A41114BBB798C98BAF38B00DB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Fortnite_Base_Tail_AnimBP_AnimGraphNode_TransitionResult_4E73C08A41114BBB798C98BAF38B00DB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Fortnite_Base_Tail_AnimBP.Fortnite_Base_Tail_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UFortnite_Base_Tail_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Fortnite_Base_Tail_AnimBP_C", "AnimGraph");

	Params::Fortnite_Base_Tail_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

