#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PunchCard

#include "Basic.hpp"

#include "PunchCard_classes.hpp"
#include "PunchCard_parameters.hpp"


namespace SDK
{

// Function PunchCard.PunchCard_C.ExecuteUbergraph_PunchCard
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPunchCard_C::ExecuteUbergraph_PunchCard(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "ExecuteUbergraph_PunchCard");

	Params::PunchCard_C_ExecuteUbergraph_PunchCard Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PunchCard.PunchCard_C.SetSuperStyle
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSuper_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPunchCard_C::SetSuperStyle(bool IsSuper_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "SetSuperStyle");

	Params::PunchCard_C_SetSuperStyle Parms{};

	Parms.IsSuper_0 = IsSuper_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PunchCard.PunchCard_C.UpdateCardCompleted
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bCompleted                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPunchCard_C::UpdateCardCompleted(bool bCompleted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "UpdateCardCompleted");

	Params::PunchCard_C_UpdateCardCompleted Parms{};

	Parms.bCompleted = bCompleted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PunchCard.PunchCard_C.On Outro Finished
// (BlueprintCallable, BlueprintEvent)

void UPunchCard_C::On_Outro_Finished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "On Outro Finished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PunchCard.PunchCard_C.FinishedPlacingMedals
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bPlayOutro                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPunchCard_C::FinishedPlacingMedals(bool bPlayOutro)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "FinishedPlacingMedals");

	Params::PunchCard_C_FinishedPlacingMedals Parms{};

	Parms.bPlayOutro = bPlayOutro;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PunchCard.PunchCard_C.On Intro Done
// (BlueprintCallable, BlueprintEvent)

void UPunchCard_C::On_Intro_Done()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "On Intro Done");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PunchCard.PunchCard_C.ShowWidget
// (Event, Protected, BlueprintEvent)

void UPunchCard_C::ShowWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "ShowWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PunchCard.PunchCard_C.MedalFInishedPlacing
// (Event, Public, BlueprintEvent)

void UPunchCard_C::MedalFInishedPlacing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "MedalFInishedPlacing");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PunchCard.PunchCard_C.RunIntroAnim
// (Event, Public, BlueprintEvent)

void UPunchCard_C::RunIntroAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "RunIntroAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PunchCard.PunchCard_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPunchCard_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PunchCard_C", "PreConstruct");

	Params::PunchCard_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

