#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassPageReward

#include "Basic.hpp"

#include "BattlePassPageReward_classes.hpp"
#include "BattlePassPageReward_parameters.hpp"


namespace SDK
{

// Function BattlePassPageReward.BattlePassPageReward_C.ExecuteUbergraph_BattlePassPageReward
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPageReward_C::ExecuteUbergraph_BattlePassPageReward(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "ExecuteUbergraph_BattlePassPageReward");

	Params::BattlePassPageReward_C_ExecuteUbergraph_BattlePassPageReward Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UBattlePassPageReward_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "OnRemovedFromFocusPath");

	Params::BattlePassPageReward_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UBattlePassPageReward_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "OnAddedToFocusPath");

	Params::BattlePassPageReward_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBattlePassPageReward_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "PreConstruct");

	Params::BattlePassPageReward_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.InitForReward
// (Event, Public, BlueprintEvent)
// Parameters:
// class UFortItemDefinition*              RewardItem                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassPageReward_C::InitForReward(const class UFortItemDefinition* RewardItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "InitForReward");

	Params::BattlePassPageReward_C_InitForReward Parms{};

	Parms.RewardItem = RewardItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.ResetToDefault
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::ResetToDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "ResetToDefault");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.SetLargeRewardVisuals
// (Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::SetLargeRewardVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "SetLargeRewardVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.SetChaseRewardVisuals
// (Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::SetChaseRewardVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "SetChaseRewardVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.UpdateVisualsToCompletedState
// (Event, Public, BlueprintEvent)

void UBattlePassPageReward_C::UpdateVisualsToCompletedState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "UpdateVisualsToCompletedState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBattlePassPageReward_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "OnMouseLeave");

	Params::BattlePassPageReward_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassPageReward.BattlePassPageReward_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BattlePassPageReward.BattlePassPageReward_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBattlePassPageReward_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassPageReward_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}

}

