#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerPawn_Athena_Phoebe

#include "Basic.hpp"

#include "PlayerPawn_Athena_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerPawn_Athena_Phoebe.BP_PlayerPawn_Athena_Phoebe_C
// 0x0010 (0x38A0 - 0x3890)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_PlayerPawn_Athena_Phoebe_C : public APlayerPawn_Athena_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PlayerPawn_Athena_Phoebe_C;      // 0x3888(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   AIEvaluator_CharacterLaunchedKeyName;              // 0x3890(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PlayerPawn_Athena_Phoebe(int32 EntryPoint);
	void OnLaunched(const struct FVector& LaunchVelocity, bool bXYOverride, bool bZOverride);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PlayerPawn_Athena_Phoebe_C">();
	}
	static class ABP_PlayerPawn_Athena_Phoebe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerPawn_Athena_Phoebe_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ABP_PlayerPawn_Athena_Phoebe_C) == 0x000010, "Wrong alignment on ABP_PlayerPawn_Athena_Phoebe_C");
static_assert(sizeof(ABP_PlayerPawn_Athena_Phoebe_C) == 0x0038A0, "Wrong size on ABP_PlayerPawn_Athena_Phoebe_C");
static_assert(offsetof(ABP_PlayerPawn_Athena_Phoebe_C, UberGraphFrame_BP_PlayerPawn_Athena_Phoebe_C) == 0x003888, "Member 'ABP_PlayerPawn_Athena_Phoebe_C::UberGraphFrame_BP_PlayerPawn_Athena_Phoebe_C' has a wrong offset!");
static_assert(offsetof(ABP_PlayerPawn_Athena_Phoebe_C, AIEvaluator_CharacterLaunchedKeyName) == 0x003890, "Member 'ABP_PlayerPawn_Athena_Phoebe_C::AIEvaluator_CharacterLaunchedKeyName' has a wrong offset!");

}

