#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_Donut_Lifesteal

#include "Basic.hpp"

#include "GA_Athena_Donut_Lifesteal_classes.hpp"
#include "GA_Athena_Donut_Lifesteal_parameters.hpp"


namespace SDK
{

// Function GA_Athena_Donut_Lifesteal.GA_Athena_Donut_Lifesteal_C.ExecuteUbergraph_GA_Athena_Donut_Lifesteal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_Donut_Lifesteal_C::ExecuteUbergraph_GA_Athena_Donut_Lifesteal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_Donut_Lifesteal_C", "ExecuteUbergraph_GA_Athena_Donut_Lifesteal");

	Params::GA_Athena_Donut_Lifesteal_C_ExecuteUbergraph_GA_Athena_Donut_Lifesteal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_Donut_Lifesteal.GA_Athena_Donut_Lifesteal_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGameplayEventData               EventData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Athena_Donut_Lifesteal_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_Donut_Lifesteal_C", "K2_ActivateAbilityFromEvent");

	Params::GA_Athena_Donut_Lifesteal_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_Donut_Lifesteal.GA_Athena_Donut_Lifesteal_C.K2_ShouldAbilityRespondToEvent
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// struct FGameplayAbilityActorInfo        ActorInfo                                              (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
// struct FGameplayEventData               Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGA_Athena_Donut_Lifesteal_C::K2_ShouldAbilityRespondToEvent(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayEventData& Payload) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_Donut_Lifesteal_C", "K2_ShouldAbilityRespondToEvent");

	Params::GA_Athena_Donut_Lifesteal_C_K2_ShouldAbilityRespondToEvent Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

