#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarshallerGliderPreset

#include "Basic.hpp"

#include "MarshallerGliderPreset_classes.hpp"
#include "MarshallerGliderPreset_parameters.hpp"


namespace SDK
{

// Function MarshallerGliderPreset.MarshallerGliderPreset_C.ExecuteUbergraph_MarshallerGliderPreset
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMarshallerGliderPreset_C::ExecuteUbergraph_MarshallerGliderPreset(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MarshallerGliderPreset_C", "ExecuteUbergraph_MarshallerGliderPreset");

	Params::MarshallerGliderPreset_C_ExecuteUbergraph_MarshallerGliderPreset Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

