#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpatialDailyScreen

#include "Basic.hpp"


namespace SDK::Params
{

// Function SpatialDailyScreen.SpatialDailyScreen_C.ExecuteUbergraph_SpatialDailyScreen
// 0x0004 (0x0004 - 0x0000)
struct SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen) == 0x000004, "Wrong alignment on SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen");
static_assert(sizeof(SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen) == 0x000004, "Wrong size on SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen");
static_assert(offsetof(SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen, EntryPoint) == 0x000000, "Member 'SpatialDailyScreen_C_ExecuteUbergraph_SpatialDailyScreen::EntryPoint' has a wrong offset!");

}

