#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VaultRotator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteUI_structs.hpp"


namespace SDK::Params
{

// Function VaultRotator.VaultRotator_C.PlaySoundWhenEnabled
// 0x0010 (0x0010 - 0x0000)
struct VaultRotator_C_PlaySoundWhenEnabled final
{
public:
	class USoundBase*                             Sound;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSoundEnabled_ReturnValue;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_PlaySoundWhenEnabled) == 0x000008, "Wrong alignment on VaultRotator_C_PlaySoundWhenEnabled");
static_assert(sizeof(VaultRotator_C_PlaySoundWhenEnabled) == 0x000010, "Wrong size on VaultRotator_C_PlaySoundWhenEnabled");
static_assert(offsetof(VaultRotator_C_PlaySoundWhenEnabled, Sound) == 0x000000, "Member 'VaultRotator_C_PlaySoundWhenEnabled::Sound' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_PlaySoundWhenEnabled, CallFunc_IsSoundEnabled_ReturnValue) == 0x000008, "Member 'VaultRotator_C_PlaySoundWhenEnabled::CallFunc_IsSoundEnabled_ReturnValue' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.SetBackgroundColor
// 0x0020 (0x0020 - 0x0000)
struct VaultRotator_C_SetBackgroundColor final
{
public:
	struct FLinearColor                           RGBA0;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           RGBA1;                                             // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VaultRotator_C_SetBackgroundColor) == 0x000004, "Wrong alignment on VaultRotator_C_SetBackgroundColor");
static_assert(sizeof(VaultRotator_C_SetBackgroundColor) == 0x000020, "Wrong size on VaultRotator_C_SetBackgroundColor");
static_assert(offsetof(VaultRotator_C_SetBackgroundColor, RGBA0) == 0x000000, "Member 'VaultRotator_C_SetBackgroundColor::RGBA0' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_SetBackgroundColor, RGBA1) == 0x000010, "Member 'VaultRotator_C_SetBackgroundColor::RGBA1' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.ToggleBackgroundText
// 0x0001 (0x0001 - 0x0000)
struct VaultRotator_C_ToggleBackgroundText final
{
public:
	bool                                          bDisplayText;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_ToggleBackgroundText) == 0x000001, "Wrong alignment on VaultRotator_C_ToggleBackgroundText");
static_assert(sizeof(VaultRotator_C_ToggleBackgroundText) == 0x000001, "Wrong size on VaultRotator_C_ToggleBackgroundText");
static_assert(offsetof(VaultRotator_C_ToggleBackgroundText, bDisplayText) == 0x000000, "Member 'VaultRotator_C_ToggleBackgroundText::bDisplayText' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.LightControl
// 0x0018 (0x0018 - 0x0000)
struct VaultRotator_C_LightControl final
{
public:
	bool                                          Active;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMobileGame_ReturnValue;                 // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsErebus_ReturnValue;                     // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsErebus_ReturnValue_1;                   // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetShadowQuality_ReturnValue;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_LightControl) == 0x000008, "Wrong alignment on VaultRotator_C_LightControl");
static_assert(sizeof(VaultRotator_C_LightControl) == 0x000018, "Wrong size on VaultRotator_C_LightControl");
static_assert(offsetof(VaultRotator_C_LightControl, Active) == 0x000000, "Member 'VaultRotator_C_LightControl::Active' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_IsMobileGame_ReturnValue) == 0x000001, "Member 'VaultRotator_C_LightControl::CallFunc_IsMobileGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_IsErebus_ReturnValue) == 0x000002, "Member 'VaultRotator_C_LightControl::CallFunc_IsErebus_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_IsErebus_ReturnValue_1) == 0x000003, "Member 'VaultRotator_C_LightControl::CallFunc_IsErebus_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_BooleanOR_ReturnValue) == 0x000004, "Member 'VaultRotator_C_LightControl::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_GetGameUserSettings_ReturnValue) == 0x000008, "Member 'VaultRotator_C_LightControl::CallFunc_GetGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_GetShadowQuality_ReturnValue) == 0x000010, "Member 'VaultRotator_C_LightControl::CallFunc_GetShadowQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000014, "Member 'VaultRotator_C_LightControl::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_BooleanOR_ReturnValue_1) == 0x000015, "Member 'VaultRotator_C_LightControl::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_LightControl, CallFunc_BooleanOR_ReturnValue_2) == 0x000016, "Member 'VaultRotator_C_LightControl::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.SwitchPCLighting
// 0x0001 (0x0001 - 0x0000)
struct VaultRotator_C_SwitchPCLighting final
{
public:
	bool                                          Visibility;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_SwitchPCLighting) == 0x000001, "Wrong alignment on VaultRotator_C_SwitchPCLighting");
static_assert(sizeof(VaultRotator_C_SwitchPCLighting) == 0x000001, "Wrong size on VaultRotator_C_SwitchPCLighting");
static_assert(offsetof(VaultRotator_C_SwitchPCLighting, Visibility) == 0x000000, "Member 'VaultRotator_C_SwitchPCLighting::Visibility' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.SwitchPCLighting_LOWDetail
// 0x0001 (0x0001 - 0x0000)
struct VaultRotator_C_SwitchPCLighting_LOWDetail final
{
public:
	bool                                          Visibility;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_SwitchPCLighting_LOWDetail) == 0x000001, "Wrong alignment on VaultRotator_C_SwitchPCLighting_LOWDetail");
static_assert(sizeof(VaultRotator_C_SwitchPCLighting_LOWDetail) == 0x000001, "Wrong size on VaultRotator_C_SwitchPCLighting_LOWDetail");
static_assert(offsetof(VaultRotator_C_SwitchPCLighting_LOWDetail, Visibility) == 0x000000, "Member 'VaultRotator_C_SwitchPCLighting_LOWDetail::Visibility' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.SwitchMobileLighting
// 0x0001 (0x0001 - 0x0000)
struct VaultRotator_C_SwitchMobileLighting final
{
public:
	bool                                          Visibility;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_SwitchMobileLighting) == 0x000001, "Wrong alignment on VaultRotator_C_SwitchMobileLighting");
static_assert(sizeof(VaultRotator_C_SwitchMobileLighting) == 0x000001, "Wrong size on VaultRotator_C_SwitchMobileLighting");
static_assert(offsetof(VaultRotator_C_SwitchMobileLighting, Visibility) == 0x000000, "Member 'VaultRotator_C_SwitchMobileLighting::Visibility' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.SetBackgroundString
// 0x0010 (0x0010 - 0x0000)
struct VaultRotator_C_SetBackgroundString final
{
public:
	int32                                         StringIndex;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_Background_Strings_C*               CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(VaultRotator_C_SetBackgroundString) == 0x000008, "Wrong alignment on VaultRotator_C_SetBackgroundString");
static_assert(sizeof(VaultRotator_C_SetBackgroundString) == 0x000010, "Wrong size on VaultRotator_C_SetBackgroundString");
static_assert(offsetof(VaultRotator_C_SetBackgroundString, StringIndex) == 0x000000, "Member 'VaultRotator_C_SetBackgroundString::StringIndex' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_SetBackgroundString, CallFunc_Create_ReturnValue) == 0x000008, "Member 'VaultRotator_C_SetBackgroundString::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.OnCameraTransitionReady
// 0x0018 (0x0018 - 0x0000)
struct VaultRotator_C_OnCameraTransitionReady final
{
public:
	bool                                          bPrimaryToSecondary;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UFortAccountItemDefinition*       PrimaryRequestedItem;                              // 0x0008(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSceneTransitionOptions                Options;                                           // 0x0010(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
static_assert(alignof(VaultRotator_C_OnCameraTransitionReady) == 0x000008, "Wrong alignment on VaultRotator_C_OnCameraTransitionReady");
static_assert(sizeof(VaultRotator_C_OnCameraTransitionReady) == 0x000018, "Wrong size on VaultRotator_C_OnCameraTransitionReady");
static_assert(offsetof(VaultRotator_C_OnCameraTransitionReady, bPrimaryToSecondary) == 0x000000, "Member 'VaultRotator_C_OnCameraTransitionReady::bPrimaryToSecondary' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_OnCameraTransitionReady, PrimaryRequestedItem) == 0x000008, "Member 'VaultRotator_C_OnCameraTransitionReady::PrimaryRequestedItem' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_OnCameraTransitionReady, Options) == 0x000010, "Member 'VaultRotator_C_OnCameraTransitionReady::Options' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.SetZoom
// 0x0001 (0x0001 - 0x0000)
struct VaultRotator_C_SetZoom final
{
public:
	bool                                          bZoomedIn;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_SetZoom) == 0x000001, "Wrong alignment on VaultRotator_C_SetZoom");
static_assert(sizeof(VaultRotator_C_SetZoom) == 0x000001, "Wrong size on VaultRotator_C_SetZoom");
static_assert(offsetof(VaultRotator_C_SetZoom, bZoomedIn) == 0x000000, "Member 'VaultRotator_C_SetZoom::bZoomedIn' has a wrong offset!");

// Function VaultRotator.VaultRotator_C.ExecuteUbergraph_VaultRotator
// 0x03D0 (0x03D0 - 0x0000)
struct VaultRotator_C_ExecuteUbergraph_VaultRotator final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMobileGame_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ETimelineDirection                            Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_BreakVector_X;                            // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0024(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x0030(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0040(0x0030)(IsPlainOldData, NoDestructor)
	float                                         CallFunc_GetTimelineLength_ReturnValue;            // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTimelineLength_ReturnValue_1;          // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetPlaybackPosition_ReturnValue;          // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetPlaybackPosition_ReturnValue_1;        // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_1;                           // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInterpolatedTransitionCamera          CallFunc_GetInterpolatedTransitionCameraPosition_ReturnValue; // 0x0090(0x0040)(NoDestructor)
	struct FHitResult                             CallFunc_K2_SetRelativeTransform_SweepHitResult;   // 0x00D0(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue;          // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetShadowQuality_ReturnValue;             // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x016C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x016D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16E[0x2];                                      // 0x016E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_2;                // 0x0170(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakVector_X_1;                          // 0x017C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y_1;                          // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z_1;                          // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_3;                // 0x0188(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_194[0xC];                                      // 0x0194(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x01A0(0x0030)(IsPlainOldData, NoDestructor)
	struct FInterpolatedTransitionCamera          CallFunc_GetInterpolatedTransitionCameraPosition_ReturnValue_1; // 0x01D0(0x0040)(NoDestructor)
	struct FHitResult                             CallFunc_K2_SetRelativeTransform_SweepHitResult_1; // 0x0210(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult;    // 0x029C(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult_1;  // 0x0328(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          K2Node_Event_bPrimaryToSecondary;                  // 0x03B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3B5[0x3];                                      // 0x03B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	const class UFortAccountItemDefinition*       K2Node_Event_PrimaryRequestedItem;                 // 0x03B8(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSceneTransitionOptions                K2Node_Event_Options;                              // 0x03C0(0x0001)(ConstParm, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x03C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bZoomedIn;                            // 0x03C2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(VaultRotator_C_ExecuteUbergraph_VaultRotator) == 0x000010, "Wrong alignment on VaultRotator_C_ExecuteUbergraph_VaultRotator");
static_assert(sizeof(VaultRotator_C_ExecuteUbergraph_VaultRotator) == 0x0003D0, "Wrong size on VaultRotator_C_ExecuteUbergraph_VaultRotator");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, EntryPoint) == 0x000000, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::EntryPoint' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_IsMobileGame_ReturnValue) == 0x000004, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_IsMobileGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, Temp_byte_Variable) == 0x000005, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, Temp_byte_Variable_1) == 0x000006, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BreakVector_X) == 0x000018, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BreakVector_Y) == 0x00001C, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BreakVector_Z) == 0x000020, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_MakeRotator_ReturnValue) == 0x000024, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_MakeRotator_ReturnValue_1) == 0x000030, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_MakeTransform_ReturnValue) == 0x000040, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetTimelineLength_ReturnValue) == 0x000070, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetTimelineLength_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetTimelineLength_ReturnValue_1) == 0x000074, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetTimelineLength_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetPlaybackPosition_ReturnValue) == 0x000078, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetPlaybackPosition_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetPlaybackPosition_ReturnValue_1) == 0x00007C, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetPlaybackPosition_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000080, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000084, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_Select_Default) == 0x000088, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_Select_Default_1) == 0x00008C, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetInterpolatedTransitionCameraPosition_ReturnValue) == 0x000090, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetInterpolatedTransitionCameraPosition_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_K2_SetRelativeTransform_SweepHitResult) == 0x0000D0, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_K2_SetRelativeTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetGameUserSettings_ReturnValue) == 0x000160, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetShadowQuality_ReturnValue) == 0x000168, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetShadowQuality_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00016C, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BooleanOR_ReturnValue) == 0x00016D, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_MakeRotator_ReturnValue_2) == 0x000170, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_MakeRotator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BreakVector_X_1) == 0x00017C, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BreakVector_Y_1) == 0x000180, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_BreakVector_Z_1) == 0x000184, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_MakeRotator_ReturnValue_3) == 0x000188, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_MakeRotator_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_MakeTransform_ReturnValue_1) == 0x0001A0, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_GetInterpolatedTransitionCameraPosition_ReturnValue_1) == 0x0001D0, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_GetInterpolatedTransitionCameraPosition_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_K2_SetRelativeTransform_SweepHitResult_1) == 0x000210, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_K2_SetRelativeTransform_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_K2_SetRelativeRotation_SweepHitResult) == 0x00029C, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_K2_SetRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, CallFunc_K2_SetRelativeRotation_SweepHitResult_1) == 0x000328, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::CallFunc_K2_SetRelativeRotation_SweepHitResult_1' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_Event_bPrimaryToSecondary) == 0x0003B4, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_Event_bPrimaryToSecondary' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_Event_PrimaryRequestedItem) == 0x0003B8, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_Event_PrimaryRequestedItem' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_Event_Options) == 0x0003C0, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_Event_Options' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_SwitchEnum_CmpSuccess) == 0x0003C1, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(VaultRotator_C_ExecuteUbergraph_VaultRotator, K2Node_Event_bZoomedIn) == 0x0003C2, "Member 'VaultRotator_C_ExecuteUbergraph_VaultRotator::K2Node_Event_bZoomedIn' has a wrong offset!");

}

